SELECT * FROM CreditScore_temp
SELECT * FROM CreditScore;

SELECT CARD_TYPE, CREDIT_NAME, CREDIT_sCORE , COUNT(*) AS C FROM
CreditScore
GROUP BY CARD_TYPE, CREDIT_NAME, CREDIT_sCORE
HAVING COUNT(*) >1;

WITH CTE AS (
	SELECT CREDIT_ID, ROW_NUMBER() OVER (PARTITION BY CARD_TYPE, CREDIT_NAME, CREDIT_SCORE ORDER BY CREDIT_ID) AS ROWNUMBER
	FROM CreditScore
	)
	DELETE FROM CreditScore
	WHERE CREDIT_ID IN ( SELECT CREDIT_ID FROM CTE WHERE ROWNUMBER > 1 );


WITH CLOUDFREKCTE AS (
	SELECT *, 
	ROW_NUMBER() OVER (PARTITION BY CARD_TYPE ORDER BY CREDIT_SCORE DESC) AS ROWNUMBER,
	RANK()		 OVER (PARTITION BY CARD_TYPE ORDER BY CREDIT_SCORE DESC) AS RANKNUMBER,
	DENSE_RANK() OVER (PARTITION BY CARD_TYPE ORDER BY CREDIT_SCORE DESC) AS DENSE_RANK
	FROM CreditScore)
SELECT * FROM CLOUDFREKCTE;

--Create a temp table for the session
 -- # hash Means local like for one session only and ## hash means global, we can use in multiple session

SELECT * INTO #TESTTMPCreditScore FROM CreditScore_temp;

SELECT * FROM #TESTTMPCreditScore;